### ISSUE TITLE
"using" property should be formatted as a bulleted list, like "required" et. al

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#292]
For consistency, and to prevent whitespace changes by text editors.

**Comment by bkeepers** [comment]
Hi @waldyrious, I'm not sure I understand. Are you talking about this list?

<img width="539" alt="eclipse_public_license_1_0_-_choosealicense_com" src="https://cloud.githubusercontent.com/assets/173/9977905/5801a25a-5ee6-11e5-9b79-5f29bf48c4d2.png">

**Comment by waldyrious** [comment]
Hi. Yes, I'm talking about that list, but just to clarify, I meant in the yaml/txt files. The change I propose would make the "using" property consistent with the other list-like properties like "required", etc.

For instance, in [epl-1.0.txt](https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/epl-1.0.txt), instead of:

```
using:
  The Eclipse Foundation: "http://www.eclipse.org"
  OpenDaylight: "http://www.opendaylight.org/"
  Clojure: "http://clojure.org/"
  JUnit: "http://junit.org/"
  Ruby: "https://github.com/jruby/jruby"
  Mondrian: "http://en.wikipedia.org/wiki/Mondrian_OLAP_server"

required:
  - disclose-source
  - include-copyright

permitted:
  - commercial-use
  - distribution
  - modifications
  - sublicense
  - patent-grant
  - private-use

forbidden:
  - no-liability
```

we'd have:

```
using:
  - The Eclipse Foundation: "http://www.eclipse.org"
  - OpenDaylight: "http://www.opendaylight.org/"
  - Clojure: "http://clojure.org/"
  - JUnit: "http://junit.org/"
  - Ruby: "https://github.com/jruby/jruby"
  - Mondrian: "http://en.wikipedia.org/wiki/Mondrian_OLAP_server"

required:
  - disclose-source
  - include-copyright

permitted:
  - commercial-use
  - distribution
  - modifications
  - sublicense
  - patent-grant
  - private-use

forbidden:
  - no-liability
```

...which, as a bonus, makes it more evident that it's a list and not hard-wrapped prose.
