### ISSUE TITLE
license yaml format issue

### ISSUE THREAD

**Issue by sify21** [github/choosealicense.com#758]
The `using` part of the license.txt looks weird to me. It's an array of single-element map like this
```yaml
using:
  - youtube-dl: https://github.com/rg3/youtube-dl/blob/master/LICENSE
  - kakoune: https://github.com/mawww/kakoune/blob/master/UNLICENSE
  - RDF.rb: https://github.com/ruby-rdf/rdf/blob/master/UNLICENSE
```
why not just use a single map like this
```yaml
using:
  youtube-dl: https://github.com/rg3/youtube-dl/blob/master/LICENSE
  kakoune: https://github.com/mawww/kakoune/blob/master/UNLICENSE
  RDF.rb: https://github.com/ruby-rdf/rdf/blob/master/UNLICENSE
```
or an array of structered map
```yaml
using:
  - name: youtube-dl
    url: https://github.com/rg3/youtube-dl/blob/master/LICENSE
  - name: kakoune
    url: https://github.com/mawww/kakoune/blob/master/UNLICENSE
  - name: RDF.rb
    url: https://github.com/ruby-rdf/rdf/blob/master/UNLICENSE
```
It makes the deserialise code boilerplate, for e.g in Rust I have to declare this field like 
```Rust
using: Option<Vec<HashMap<String, String>>>,
```
When using this `using` field, I have to iterate the vector, during which I have to iterate the single-element map!
In other formats, it would be
```Rust
using: Option<HashMap<String, String>>,
```
or
```Rust
using: Option<Vec<SomeStruct>>,
```
